Set visibility of popovers, avoid trigger when hovering invisible pseudoelement
papercss/papercss pull request #298
Opened 2023-03-14 16:46 UTC by donmccurdy

## Brief description

This PR is intended to fix #297, such that popovers do not appear when hovering over the area occupied by the (still invisible) popover. This can be important if other elements are beneath that area, and also [improves accessibility](https://css-tricks.com/snippets/css/toggle-visibility-when-hiding-elements/).

Unfortunately I'm having trouble getting the local development server running to test this change. In CONTRIBUTING.md I don't see anything about installing Hugo — do I need to do anything manually there? I'm on macOS. When running `npm run dev` I get errors like "node_modules/hugo-bin/vendor EACCES", or when installing Hugo manually and running ` hugo server --source=docs --disableFastRender` I get the error:

> `Configured defaultMarkdownHandler "blackfriday" not found. Did you mean to use goldmark? Blackfriday was removed in Hugo v0.100.0."`

I tried manually switching the markdown handler, Hugo runs and the site loads, but the demo PaperCSS components are missing from the site preview.

Thanks!

## Developer Certificate of Origin

- [x] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

## Sample pictures

N/A

## Further details

- Fixes #297

2023-03-15 12:03 UTC, Oli8 requested changes

2023-03-15 12:03 UTC, Oli8 commented on src/components/_popovers.scss
> +      transition: opacity 0.2s ease-out, visibility 0s linear 0s;
`opacity 235ms ease-in-out` are the original transition values, probably better to stick to it.
The last `0s` is not needed as it is the default. 
```suggestion
      transition: opacity 235ms ease-in-out, visibility 0s linear;
```

2023-03-15 12:03 UTC, Oli8 commented on src/components/_popovers.scss
> +    transition: opacity 0.2s ease-out, visibility 0s linear 0.2s;
Same as above, also you should remove the line with `@include transition(opacity);` as it is now overridden.
```suggestion
    transition: opacity 235ms ease-in-out, visibility 0s linear 0.2s;
```

2023-03-15 13:49 UTC, donmccurdy commented
Updates applied, thanks @Oli8!

2023-03-15 14:29 UTC, donmccurdy commented
Oh, that's where the original value came from! I'd missed the scss macro yes, thanks. Fixed!

2023-03-15 14:33 UTC, Oli8 approved these changes

2023-05-24 10:50 UTC, Oli8 commented
:stop_sign:  Need someone allowed to merge to master and make a patch release

2023-05-29 18:44 UTC, merged

2023-05-29 18:45 UTC, rhyneav commented
Thanks y'all! Just merged and published `v1.9.2"